trigger:
  branches:
    include: [ "*" ]
  tags:
    include: [ "*" ]

pool:
  name: WS

resources:
  repositories:
  - repository: azureCI
    type: git
    name: azureCI
    
variables:
  COMPONENT: catalogue
    
stages: 
- template: "codecheck.yml@azureCI"
- template: "codeTest.yml@azureCI"
- template: "nodejs-az.yml@azureCI"
  